title: inmidvideo
email: dan@inmidvideo.com
description: ""
baseurl: ""
url: https://inmidvideo.com
twitter_username: inmidvideo
github_username:  inmidvideo

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
